version: '3'

networks:
  my-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    # image: mongodb/mongodb-community-server:latest
    pull_policy: always
    container_name: mongodb
    restart: unless-stopped
    # command: ["/bin/bash", "-c", "echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled && mongod --smallfiles"]
    # command: ["sysctl", "-w", "vm.max_map_count=262144"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=your_db_user
      - MONGO_INITDB_ROOT_PASSWORD=your_db_pass
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-network
    labels:
      app: mongodb
      kompose.service.type: 'NodePort'

volumes:
  mongodb_data:
    # driver: local
