apiVersion: v1
kind: Service
metadata:
  annotations:
    app: redis
    kompose.service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
  namespace: default
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis
  type: NodePort
status:
  loadBalancer: {}
