// Path: src/common/constant/repository.constant.ts
// DESC: general repository types
'use strict';
export const REPOSITORY_DEVICE_TYPES = ['file', 'database'];
export const DEFAULT_REPOSITORY_DEVICE_TYPE =
  process.env.REPOSITORY_DEVICE_TYPE || REPOSITORY_DEVICE_TYPES[1];

export const FILE_REPOSITORY_DEVICE_TYPES = ['json', 'yaml', 'csv', 'md'];
export const DEFAULT_FILE_REPOSITORY_DEVICE_TYPE =
  process.env.FILE_REPOSITORY_DEVICE_TYPE || FILE_REPOSITORY_DEVICE_TYPES[0];
export const DEFAULT_FILE_REPOSITORY_EXTENSION = FILE_REPOSITORY_DEVICE_TYPES[0];

export const DATABASE_REPOSITORY_DEVICE_TYPES = ['memory', 'sqlite', 'mongodb', 'postgres'];
export const DEFAULT_DATABASE_REPOSITORY_DEVICE_TYPE =
  process.env.DATABASE_REPOSITORY_DEVICE_TYPE || DATABASE_REPOSITORY_DEVICE_TYPES[3];

export const REPOSITORY_FILE_TYPE = ['single', 'multiple'];
export const DEFAULT_REPOSITORY_FILE_TYPE = REPOSITORY_FILE_TYPE[1];

const DEFAULT_ROOT_PROJECT_PATH = '.';

export const DEFAULT_PROJECT_NAME = 'scrum-project';
export const DEFAULT_PROJECT_FILE_NAME = 'project.json';
export const DEFAULT_PROJECT_PATH = `${DEFAULT_ROOT_PROJECT_PATH}/.${DEFAULT_PROJECT_NAME}`;
export const DEFAULT_PROJECT_FILE_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_PROJECT_FILE_NAME}`;

export const DEFAULT_TEAM_NAME = 'team';
export const DEFAULT_TEAM_FILE_NAME = 'team.json';
export const DEFAULT_TEAM_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_TEAM_NAME}`;
export const DEFAULT_TEAM_FILE_PATH = `${DEFAULT_TEAM_PATH}/${DEFAULT_TEAM_FILE_NAME}`;

export const DEFAULT_USER_NAME = 'user';
export const DEFAULT_USER_FILE_NAME = 'user.json';
export const DEFAULT_USER_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_USER_NAME}`;
export const DEFAULT_USER_FILE_PATH = `${DEFAULT_USER_PATH}/${DEFAULT_USER_FILE_NAME}`;

export const DEFAULT_ITERATION_NAME = 'iteration';
export const DEFAULT_ITERATION_FILE_NAME = 'iteration.json';
export const DEFAULT_ITERATION_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_ITERATION_NAME}`;
export const DEFAULT_ITERATION_FILE_PATH = `${DEFAULT_ITERATION_PATH}/${DEFAULT_ITERATION_FILE_NAME}`;

export const DEFAULT_TASK_NAME = 'task';
export const DEFAULT_TASK_FILE_NAME = 'task.json';
export const DEFAULT_TASK_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_TASK_NAME}`;
export const DEFAULT_TASK_FILE_PATH = `${DEFAULT_TASK_PATH}/${DEFAULT_TASK_FILE_NAME}`;

export const DEFAULT_METRIC_NAME = 'metric';
export const DEFAULT_METRIC_FILE_NAME = 'metric.json';
export const DEFAULT_METRIC_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_METRIC_NAME}`;
export const DEFAULT_METRIC_FILE_PATH = `${DEFAULT_METRIC_PATH}/${DEFAULT_METRIC_FILE_NAME}`;

export const DEFAULT_COMMENT_NAME = 'message';
export const DEFAULT_COMMENT_FILE_NAME = 'message.json';
export const DEFAULT_COMMENT_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_COMMENT_NAME}`;
export const DEFAULT_COMMENT_FILE_PATH = `${DEFAULT_COMMENT_PATH}/${DEFAULT_COMMENT_FILE_NAME}`;
