// This file is autogenerated by the script.
// Do not edit this file directly.
import 'reflect-metadata';
export * from './memory-user.repository';
export * from './multiple-json-files-user.repository';
export * from './prisma-mongodb-user.repository';
export * from './prisma-postgres-user.repository';
export * from './single-json-file-user.repository';
export * from './user-repository.interface';
export * from './user.repository';
