version: '3'

networks:
  my-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    pull_policy: always
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_pass
      - POSTGRES_DB=your_db_name
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
    labels:
      app: postgres
      kompose.service.type: 'NodePort'

volumes:
  postgres_data:
    driver: local
