apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: mongodb
    kompose.service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        app: mongodb
        kompose.service.type: NodePort
      creationTimestamp: null
      labels:
        io.kompose.network/docker-compose-my-network: "true"
        io.kompose.service: mongodb
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: your_db_pass
            - name: MONGO_INITDB_ROOT_USERNAME
              value: your_db_user
          image: mongo:latest
          name: mongodb
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      restartPolicy: Always
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
status: {}
