// This file is autogenerated by the script.
// Do not edit this file directly.
import 'reflect-metadata';
export * from './memory-team.repository';
export * from './multiple-json-files-team.repository';
export * from './prisma-mongodb-team.repository';
export * from './prisma-postgres-team.repository';
export * from './single-json-file-team.repository';
export * from './team-repository.interface';
export * from './team.repository';
